//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D365FO_Table_browser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("D365FO_Table_browser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To open a table the company account, server and table must be selected from the combo boxes. You can add more tables for fast access from the tables menu.
        /// </summary>
        internal static string CantOpenTable {
            get {
                return ResourceManager.GetString("CantOpenTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object used in the compare is null.
        /// </summary>
        internal static string CompareObjIsNull {
            get {
                return ResourceManager.GetString("CompareObjIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm action.
        /// </summary>
        internal static string ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the tab: &quot;{0}&quot; ?.
        /// </summary>
        internal static string ConfirmCloseTab {
            get {
                return ResourceManager.GetString("ConfirmCloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected account will be permanently removed ({0}) Continue?.
        /// </summary>
        internal static string ConfirmRemovalOfCompanyAccount {
            get {
                return ResourceManager.GetString("ConfirmRemovalOfCompanyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the selected company accounts will be removed, {0} accounts will be removed, continue?.
        /// </summary>
        internal static string ConfirmRemovalOfCompanyAccounts {
            get {
                return ResourceManager.GetString("ConfirmRemovalOfCompanyAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected server will be permanently removed ({0}) Continue?.
        /// </summary>
        internal static string ConfirmRemovalOfServer {
            get {
                return ResourceManager.GetString("ConfirmRemovalOfServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the selected servers will be removed, {0} servers will be removed, continue?.
        /// </summary>
        internal static string ConfirmRemovalOfServers {
            get {
                return ResourceManager.GetString("ConfirmRemovalOfServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected table will be permanently removed ({0}) Continue?.
        /// </summary>
        internal static string ConfirmRemovalOfTable {
            get {
                return ResourceManager.GetString("ConfirmRemovalOfTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the selected tables will be removed, {0} tables will be removed, continue?.
        /// </summary>
        internal static string ConfirmRemovalOfTables {
            get {
                return ResourceManager.GetString("ConfirmRemovalOfTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the last tab, keep it open.
        /// </summary>
        internal static string LastTab {
            get {
                return ResourceManager.GetString("LastTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last tab selected.
        /// </summary>
        internal static string LastTabWarning {
            get {
                return ResourceManager.GetString("LastTabWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a table to browse from the list.
        /// </summary>
        internal static string NoTable {
            get {
                return ResourceManager.GetString("NoTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click open the selected table button to browse: {0}.
        /// </summary>
        internal static string SelectedTable {
            get {
                return ResourceManager.GetString("SelectedTable", resourceCulture);
            }
        }
    }
}
